### ISSUE TITLE
Implement the Dropout Report selection screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#176]
![252795241](https://user-images.githubusercontent.com/3488986/33160439-7419ef6e-d02d-11e7-9dba-67e37b2e1c16.png)

This is the screen that the user sees when she selects the Dropout Report module in the ZEIR app side menu (https://github.com/OpenSRP/opensrp-client-path/issues/186). Each row is tappable and opens up that report:

- [x] BCG-Measles Cumulative opens https://github.com/OpenSRP/opensrp-client-path/issues/177
- [x] BCG-Measles Cohort opens https://github.com/OpenSRP/opensrp-client-path/issues/178
- [x] Penta Cumulative opens https://github.com/OpenSRP/opensrp-client-path/issues/179
- [x] Penta Cohort opens https://github.com/OpenSRP/opensrp-client-path/issues/180
- [x] Measles Cumulative opens https://github.com/OpenSRP/opensrp-client-path/issues/181

NB: The back arrow in the mockup above should be replaced with the user initials (similar to HIA2 report and stock module).

Also, the dropout icon has been updated. Please use the dropout icon asset from this issue (https://github.com/OpenSRP/opensrp-client-path/issues/170#issuecomment-347569772) instead.

**Comment by cagulas** [comment]
Results from QA on 29 January (V1.3.2.1):

Nothing, lgtm!
